version: '3'

services:
  next-app:
    container_name: viva
    image: ngotheson/viva:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API: ${NEXT_PUBLIC_API}
        DOMAIN: ${DOMAIN}
        SITE_NAME: ${SITE_NAME}
        NEXT_PUBLIC_RECAPCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPCHA_SITE_KEY}
        RECAPCHA_SECRET_KEY: ${RECAPCHA_SECRET_KEY}
        NEXT_PUBLIC_REVALIDATE: ${NEXT_PUBLIC_REVALIDATE}
    restart: always
    ports:
      - 3001:3000
    networks:
      - asivivatravel

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  asivivatravel:
    external: true
